{
 "title": "Growth",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "my_ticker",
    "label": "tickers",
    "query": "SELECT\n  \"ticker\"\nFROM \"incomeStatementHistory\"\n"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FCF / Revenue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker AS metric,\n  \"freeCashflow\"*100/\"totalRevenue\"\nFROM fin_data\nWHERE ticker = '$my_ticker'"
    }
   ]
  },
  {
   "title": "Cash / Debt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker AS metric,\n  \"totalCash\"*100/\"totalDebt\"\nFROM fin_data\nWHERE ticker = '$my_ticker'"
    }
   ]
  },
  {
   "title": "Debt Ratios",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker AS metric,\n  \"currentRatio\", \"quickRatio\"\nFROM fin_data\nWHERE ticker = '$my_ticker'"
    }
   ]
  },
  {
   "title": "Growth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker AS metric,\n  \"revenueGrowth\", \"earningsGrowth\"\nFROM fin_data\nWHERE ticker = '$my_ticker'"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker AS metric,\n  \"returnOnEquity\", \"returnOnAssets\"\nFROM fin_data\nWHERE ticker = '$my_ticker'"
    }
   ]
  },
  {
   "title": "Total Revenue and Free Cash Flow",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sql_date AS \"time\",\n  date AS metric,\n  \"totalRevenue\"\nFROM \"incomeStatementHistory\"\nWHERE\n  $__timeFilter(sql_date) AND\n  ticker = '$my_ticker'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  sql_date AS \"time\",\n  date AS metric,\n  \"totalCashFromOperatingActivities\" + \"capitalExpenditures\"\nFROM \"cashflowStatementHistory\"\nWHERE\n  $__timeFilter(sql_date) AND\n  ticker = '$my_ticker'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total Revenue and Free Cash Flow Quarterly",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sql_date AS \"time\",\n  date AS metric,\n  \"totalRevenue\"\nFROM \"incomeStatementHistoryQuarterly\"\nWHERE\n  $__timeFilter(sql_date) AND\n  ticker = '$my_ticker'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  sql_date AS \"time\",\n  date AS metric,\n  \"totalCashFromOperatingActivities\" + \"capitalExpenditures\"\nFROM \"cashflowStatementHistoryQuarterly\"\nWHERE\n  $__timeFilter(sql_date) AND\n  ticker = '$my_ticker'\nORDER BY 1,2"
    }
   ]
  }
 ]
}